#!/bin/sh
# BSD HEADER START
# This file is part of zxfer project.

# Copyright (c) 2024-2026 Aldo Gonzalez
# Copyright (c) 2013-2019 Allan Jude <allanjude@freebsd.org>
# Copyright (c) 2010,2011 Ivan Nash Dreckman
# Copyright (c) 2007,2008 Constantin Gonzalez
# All rights reserved.

# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:

#     * Redistributions of source code must retain the above copyright notice,
#       this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright notice,
#       this list of conditions and the following disclaimer in the documentation
#       and/or other materials provided with the distribution.

# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# BSD HEADER END
# shellcheck shell=sh disable=SC2034,SC2154

#
# zxfer
#
# ZFS-native snapshot replication for local and remote OpenZFS systems.
# Uses `zfs send` / `zfs receive` with property synchronization, secure helper
# resolution, and structured failure reporting.

# Purpose: Print the usage synopsis.
# Usage: zxfer_usage; -h prints it to stdout, and the usage throws in
# src/zxfer_reporting.sh print it to stderr (a call shellcheck cannot see).
# shellcheck disable=SC2329
zxfer_usage() {
	cat <<EOT
usage:
     zxfer [-b | -B] [-c FMRI|pattern[ FMRI|pattern]...] [-d] [-D 'progress dialog options']
           [-e | -k] [-F] [-g days] [-I properties,to,ignore] [-j #jobs] [-m] [-n]
           {-N path/to/src | -R path/to/src} [-o option1=value1,option2=value2...]
           [-O user@host] [-P] [-s] [-T user@host] [-U] [-v] [-V] [-w]
           [-x pattern] [-Y] [-z] [-Z "full zstd compression command"]
           destination
     zxfer [-h]

           Where destination is a ZFS filesystem e.g.  poolname/fsname

zxfer has a man page that explains each of the options in detail, along with
usage examples. To access the man page, type:
$ man zxfer

EOT
}

# Bootstrap with the built-in allowlist before sourcing helpers so early startup
# never executes PATH-injected awk/sed binaries. zxfer_init_session_environment()
# later applies the configurable secure PATH derived from
# ZXFER_SECURE_PATH(_APPEND).
ZXFER_EARLY_DEFAULT_SECURE_PATH="/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"
PATH=$ZXFER_EARLY_DEFAULT_SECURE_PATH
export PATH

# Purpose: Print usage and exit 0 when -h appears before any module loads.
# Usage: zxfer_prescan_help_flag "$@"
zxfer_prescan_help_flag() {
	l_opt=""
	OPTIND=1
	while getopts ":h" l_opt "$@"; do
		case $l_opt in
		h)
			zxfer_usage
			exit 0
			;;
		*) ;;
		esac
	done
	OPTIND=1
}

###############################################################################
# MAIN
###############################################################################

zxfer_prescan_help_flag "$@"

# Tell the profiler before option parsing whether -V may be active, so it
# reads the start clock only then (zxfer_reset_profile_state): any
# short-option cluster containing V counts, and an option argument that merely
# contains V costs one clock read.
g_zxfer_profile_prescan=0
for l_prescan_arg in "$@"; do
	case $l_prescan_arg in
	-*V*) g_zxfer_profile_prescan=1 ;;
	esac
done

# Source runtime modules from this project; ${0%/*} is dirname without a fork.
case $0 in
*/*) zxfer_launcher_dir=${0%/*} ;;
*) zxfer_launcher_dir=. ;;
esac
[ -n "$zxfer_launcher_dir" ] || zxfer_launcher_dir=/
ZXFER_SOURCE_MODULES_ROOT=$zxfer_launcher_dir
# shellcheck source=src/zxfer_modules.sh
. "$zxfer_launcher_dir"/src/zxfer_modules.sh
zxfer_load_modules || exit $?

# Rendering the invocation can run ${g_cmd_awk:-awk} before dependency
# resolution assigns g_cmd_awk, so an inherited value must never be used:
# only the awk on the pinned PATH above may run.
unset g_cmd_awk
zxfer_set_original_invocation "$0" "$@"

zxfer_main "$@"
exit $?
