#!/bin/sh
# BSD HEADER START
# This file is part of zxfer project.

# Copyright (c) 2024-2026 Aldo Gonzalez
# Copyright (c) 2013-2019 Allan Jude <allanjude@freebsd.org>
# Copyright (c) 2010,2011 Ivan Nash Dreckman
# Copyright (c) 2007,2008 Constantin Gonzalez
# All rights reserved.

# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:

#     * Redistributions of source code must retain the above copyright notice,
#       this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright notice,
#       this list of conditions and the following disclaimer in the documentation
#       and/or other materials provided with the distribution.

# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# BSD HEADER END

#
# zxfer
#
# ZFS-native snapshot replication for local and remote OpenZFS systems.
# Uses `zfs send` / `zfs receive` with property synchronization, secure helper
# resolution, and structured failure reporting.

#
# Print out usage information
# shellcheck disable=SC2329
# usage() is called indirectly via throw_usage_error() in src/zxfer_common.sh.
usage() {
	cat <<EOT
usage:
     zxfer [-dFnPsUvVwY] [-x pattern ] [-j #jobs] [-k | -e] [-b | -B] {-N path/to/src | -R path/to/src}
           [-z] [-Z "full zstd compression command"]
           [-m [c FMRI|pattern[ FMRI|pattern]...]]] [-O user@host]
           [-D 'progress dialog options'] [-I properties,to,ignore]
           [-T user@host] [-o option1=value1,option2=value2...] [-g days]
           destination
     zxfer [-h]

           Where destination is a ZFS filesystem e.g.  poolname/fsname

zxfer has a man page that explains each of the options in detail, along with
usage examples. To access the man page, type:
$ man zxfer

EOT
}

# Bootstrap with the built-in allowlist before sourcing helpers so early startup
# never executes PATH-injected awk/sed binaries. init_globals() later applies the
# configurable secure PATH derived from ZXFER_SECURE_PATH(_APPEND).
ZXFER_EARLY_DEFAULT_SECURE_PATH="/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"
PATH=$ZXFER_EARLY_DEFAULT_SECURE_PATH
export PATH

zxfer_prescan_help_flag() {
	l_opt=""
	OPTIND=1
	while getopts ":h" l_opt "$@"; do
		case $l_opt in
		h)
			usage
			exit 0
			;;
		*) ;;
		esac
	done
	OPTIND=1
}

zxfer_escape_report_value_early() {
	printf '%s' "$1" | awk '
BEGIN {
	ORS = ""
}
{
	if (NR > 1) {
		printf "\\n"
	}
	line = $0
	gsub(/\\/, "\\\\", line)
	gsub(/\t/, "\\t", line)
	gsub(/\r/, "\\r", line)
	printf "%s", line
}
'
}

zxfer_quote_token_for_report_early() {
	l_value_escaped=$(zxfer_escape_report_value_early "$1")
	l_value_safe=$(printf '%s' "$l_value_escaped" | sed "s/'/'\"'\"'/g")
	printf "'%s'" "$l_value_safe"
}

g_zxfer_original_invocation=$(zxfer_quote_token_for_report_early "$0")
for l_zxfer_arg in "$@"; do
	l_zxfer_quoted_arg=$(zxfer_quote_token_for_report_early "$l_zxfer_arg")
	g_zxfer_original_invocation="$g_zxfer_original_invocation $l_zxfer_quoted_arg"
done
g_zxfer_failure_stage=startup

###############################################################################
# MAIN
###############################################################################

zxfer_prescan_help_flag "$@"

# Source other scripts from this project
dir=$(dirname "$0")
. "$dir"/src/zxfer_common.sh
. "$dir"/src/zxfer_globals.sh
. "$dir"/src/zxfer_transfer_properties.sh

. "$dir"/src/zxfer_zfs_mode.sh
. "$dir"/src/zxfer_get_zfs_list.sh
. "$dir"/src/zxfer_zfs_send_receive.sh
. "$dir"/src/zxfer_inspect_delete_snap.sh

init_globals

zxfer_set_failure_stage "cli parse"
read_command_line_switches "$@"

# Read out source and dest values
shift "$((OPTIND - 1))"
g_destination=$1

# Basic consistency checking
if [ $# -lt 1 ]; then
	throw_usage_error "Need a destination."
fi

zxfer_set_failure_roots "" "$g_destination"
zxfer_set_failure_stage "cli validation"
consistency_check
prepare_remote_host_connections
init_variables

zxfer_set_failure_stage "replication"
run_zfs_mode_loop

# writes property backup info to file
if [ "$g_option_k_backup_property_mode" -eq 1 ]; then
	write_backup_properties
fi

# exit with success
beep 0
exit 0
