#!/bin/sh
#
# Shared mock-toolchain helpers for black-box driving ./zxfer with a canned
# zfs and counting wrappers. Sourced by shunit2 suites and bench runners:
#   tests/test_zxfer_mock_toolchain.sh (self-test)
#   tests/test_zxfer_planning_blackbox.sh
#   tests/run_microbench.sh / tests/test_zxfer_microbench_budgets.sh
#
# Standalone by design: no dependency on the integration harness. The only
# host requirements are POSIX sh plus the standard userland already required
# by zxfer itself.
#
# Canned zfs runtime environment (read by the generated mock zfs script):
#   MOCK_ZFS_LOG            append-only argv log; one invocation per line,
#                           argv joined with single spaces, mutating
#                           subcommands prefixed with "MUTATE ". Unset or
#                           empty disables logging.
#   MOCK_ZFS_FIXTURE_DIR    directory containing "manifest" plus fixture
#                           files for read-only discovery answers.
#   MOCK_ZFS_DEFAULT_STATUS exit status for unmatched read-only commands
#                           (default 1).
#
# Manifest format ($MOCK_ZFS_FIXTURE_DIR/manifest), one rule per line:
#   <glob-pattern><TAB><fixture-file><TAB><exit-status>
# The pattern is matched (sh case glob, first match wins) against the argv
# key: all zfs arguments joined with single spaces, e.g.
#   "list -Hr -o name,guid -s creation -t snapshot srcpool/data".
# <fixture-file> is relative to $MOCK_ZFS_FIXTURE_DIR; "-" emits no output.
# <exit-status> defaults to 0 when omitted. Lines starting with "#" and
# blank lines are skipped. "|" alternation is not supported; use one
# pattern per line.
#
# Counting wrapper runtime environment:
#   MOCK_SPAWN_LOG          append-only spawn log; one tool name per line.
#                           Unset logs to /dev/null (no counting overhead).
#
# shellcheck shell=sh

# Fixed fixture topology used by zxfer_mockbin_build_fixture_tree. Constants
# so suites and bench runners reference one source of truth for the dataset
# names the manifests are keyed on.
ZXFER_MOCKBIN_SOURCE_ROOT="srcpool/data"
ZXFER_MOCKBIN_DEST_ROOT="dstpool/back"
ZXFER_MOCKBIN_DEST_MAPPED_ROOT="dstpool/back/data"
ZXFER_MOCKBIN_SYSTEM_SECURE_PATH="/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"

# Purpose: Resolve one host tool to an absolute path from the caller's PATH.
# Usage: Internal lookup for zxfer_mockbin_prepare_dir and counting-wrapper
# callers that need the real binary location before shadowing it.
# Returns: Absolute path on stdout, or status 1 with a stderr note.
zxfer_mockbin_resolve_host_tool() {
	l_mockbin_tool=$1

	l_mockbin_resolved=$(command -v "$l_mockbin_tool" 2>/dev/null || :)
	case "$l_mockbin_resolved" in
	/*)
		printf '%s\n' "$l_mockbin_resolved"
		return 0
		;;
	esac

	printf 'mock_toolchain_helper: required host tool not found: %s\n' \
		"$l_mockbin_tool" >&2
	return 1
}

# Purpose: Symlink real host tools into a mock bin directory so zxfer can
# resolve them through a secure PATH that leads with that directory.
# Usage: zxfer_mockbin_prepare_dir <dir> <real-tool>... — creates <dir> when
# missing and replaces existing entries, so it is safe to call repeatedly or
# after dropping a canned zfs into the same directory.
zxfer_mockbin_prepare_dir() {
	l_mockbin_dir=$1
	shift

	mkdir -p "$l_mockbin_dir" || return 1

	for l_mockbin_entry in "$@"; do
		l_mockbin_real=$(zxfer_mockbin_resolve_host_tool "$l_mockbin_entry") ||
			return 1
		ln -sf "$l_mockbin_real" "$l_mockbin_dir/$l_mockbin_entry" || return 1
	done
}

# Purpose: Write the canned zfs mock that logs every invocation and answers
# read-only discovery from a manifest-driven fixture directory.
# Usage: zxfer_mockbin_write_canned_zfs <path> — typically
# <mockdir>/zfs so the secure PATH resolves it ahead of any real zfs.
# Side effects: Overwrites <path> and marks it executable. Behavior of the
# generated script:
#   - every argv is appended to $MOCK_ZFS_LOG (space-joined, one line);
#   - destroy/rollback/create/set/inherit/snapshot/rename/clone/promote/
#     hold/release/bookmark are logged with a "MUTATE " prefix and exit per
#     manifest (default 0);
#   - receive/recv consumes stdin to /dev/null and exits per manifest
#     (default 0), logged without the MUTATE prefix;
#   - send emits matched fixture bytes, or a one-line dummy stream when
#     unmatched, and exits per manifest (default 0);
#   - all other subcommands are read-only: matched rules emit the fixture
#     and exit with the rule status; unmatched commands print a stderr note
#     and exit $MOCK_ZFS_DEFAULT_STATUS (default 1).
zxfer_mockbin_write_canned_zfs() {
	l_mockbin_zfs_path=$1

	cat >"$l_mockbin_zfs_path" <<'EOF'
#!/bin/sh
# Canned zfs mock generated by tests/mock_toolchain_helper.sh.
# See that helper's header comment for the manifest and env contract.

mock_key=$*
mock_fixture=""
mock_status=0

mock_log_line() {
	if [ -n "${MOCK_ZFS_LOG:-}" ]; then
		printf '%s\n' "$1" >>"$MOCK_ZFS_LOG"
	fi
}

# First manifest rule whose glob pattern matches the space-joined argv wins.
mock_manifest_lookup() {
	[ -n "${MOCK_ZFS_FIXTURE_DIR:-}" ] || return 1
	mock_manifest="$MOCK_ZFS_FIXTURE_DIR/manifest"
	[ -r "$mock_manifest" ] || return 1
	mock_tab=$(printf '\t')
	while IFS=$mock_tab read -r mock_pattern mock_rule_fixture mock_rule_status; do
		case "$mock_pattern" in
		'' | '#'*)
			continue
			;;
		esac
		# shellcheck disable=SC2254  # manifest patterns glob-match on purpose
		case "$mock_key" in
		$mock_pattern)
			mock_fixture=$mock_rule_fixture
			mock_status=${mock_rule_status:-0}
			return 0
			;;
		esac
	done <"$mock_manifest"
	return 1
}

mock_emit_fixture() {
	if [ -n "$mock_fixture" ] && [ "$mock_fixture" != "-" ]; then
		cat "$MOCK_ZFS_FIXTURE_DIR/$mock_fixture"
	fi
}

case "${1:-}" in
destroy | rollback | create | set | inherit | snapshot | rename | clone | promote | hold | release | bookmark)
	mock_log_line "MUTATE $mock_key"
	if mock_manifest_lookup; then
		mock_emit_fixture
		exit "$mock_status"
	fi
	exit 0
	;;
receive | recv)
	mock_log_line "$mock_key"
	cat >/dev/null
	if mock_manifest_lookup; then
		mock_emit_fixture
		exit "$mock_status"
	fi
	exit 0
	;;
send)
	mock_log_line "$mock_key"
	if mock_manifest_lookup; then
		mock_emit_fixture
		exit "$mock_status"
	fi
	printf 'ZXFERMOCKSTREAM %s\n' "$mock_key"
	exit 0
	;;
*)
	mock_log_line "$mock_key"
	if mock_manifest_lookup; then
		mock_emit_fixture
		exit "$mock_status"
	fi
	printf 'mock zfs: no manifest match for: %s\n' "$mock_key" >&2
	exit "${MOCK_ZFS_DEFAULT_STATUS:-1}"
	;;
esac
EOF
	chmod +x "$l_mockbin_zfs_path"
}

# Purpose: Write a minimal counting wrapper that records one spawn per
# invocation and then execs the real tool unchanged.
# Usage: zxfer_mockbin_write_counting_wrapper <path> <real-tool-abs-path> —
# the logged name is the basename of <path>; place the wrapper in the mock
# bin directory so it shadows the system tool via the secure PATH.
zxfer_mockbin_write_counting_wrapper() {
	l_mockbin_wrapper_path=$1
	l_mockbin_wrapper_real=$2

	case "$l_mockbin_wrapper_real" in
	/*) ;;
	*)
		printf 'zxfer_mockbin_write_counting_wrapper: real tool path must be absolute: %s\n' \
			"$l_mockbin_wrapper_real" >&2
		return 1
		;;
	esac
	if [ ! -x "$l_mockbin_wrapper_real" ]; then
		printf 'zxfer_mockbin_write_counting_wrapper: real tool not executable: %s\n' \
			"$l_mockbin_wrapper_real" >&2
		return 1
	fi

	l_mockbin_wrapper_name=${l_mockbin_wrapper_path##*/}
	{
		printf '#!/bin/sh\n'
		# shellcheck disable=SC2016  # MOCK_SPAWN_LOG must expand at wrapper runtime
		printf 'printf '\''%%s\\n'\'' "%s" >>"${MOCK_SPAWN_LOG:-/dev/null}"\n' \
			"$l_mockbin_wrapper_name"
		printf 'exec "%s" "$@"\n' "$l_mockbin_wrapper_real"
	} >"$l_mockbin_wrapper_path"
	chmod +x "$l_mockbin_wrapper_path"
}

# Purpose: Emit name<TAB>guid snapshot records for the fixture tree with
# deterministic 19-digit guids derived from dataset and snapshot indexes.
# Usage: Internal generator shared by the fixture-state writer. Arguments:
# <root-dataset> <dataset-count> <snap-count> <order> where order
# "creation" interleaves snapshot-major (mimics `zfs list -s creation -r`)
# and "dataset" groups dataset-major (mimics plain `zfs list -r`).
zxfer_mockbin_emit_snapshot_records() {
	l_mockbin_emit_root=$1
	l_mockbin_emit_datasets=$2
	l_mockbin_emit_snaps=$3
	l_mockbin_emit_order=$4

	awk -v root="$l_mockbin_emit_root" -v n="$l_mockbin_emit_datasets" \
		-v s="$l_mockbin_emit_snaps" -v order="$l_mockbin_emit_order" '
		function dataset_name(d) {
			return (d == 0) ? root : root "/child" d
		}
		# guid layout: "1" + 4-digit dataset idx + 5-digit snap idx +
		# 9-digit constant = 19 deterministic digits.
		function guid(d, i) {
			return sprintf("1%04d%05d%09d", d, i, 7)
		}
		BEGIN {
			if (order == "creation") {
				for (i = 1; i <= s; i++)
					for (d = 0; d <= n; d++)
						printf "%s@snap%d\t%s\n", dataset_name(d), i, guid(d, i)
			} else {
				for (d = 0; d <= n; d++)
					for (i = 1; i <= s; i++)
						printf "%s@snap%d\t%s\n", dataset_name(d), i, guid(d, i)
			}
		}
	'
}

# Purpose: Write one complete canned-zfs fixture state directory (fixture
# files plus manifest) for a given destination snapshot depth.
# Usage: Internal writer for zxfer_mockbin_build_fixture_tree. Arguments:
# <state-dir> <dataset-count> <src-snaps> <dst-snaps>.
zxfer_mockbin_write_fixture_state_dir() {
	l_mockbin_state_dir=$1
	l_mockbin_state_datasets=$2
	l_mockbin_state_src_snaps=$3
	l_mockbin_state_dst_snaps=$4

	mkdir -p "$l_mockbin_state_dir" || return 1

	zxfer_mockbin_emit_snapshot_records "$ZXFER_MOCKBIN_SOURCE_ROOT" \
		"$l_mockbin_state_datasets" "$l_mockbin_state_src_snaps" creation \
		>"$l_mockbin_state_dir/src_snapshots.list" || return 1
	zxfer_mockbin_emit_snapshot_records "$ZXFER_MOCKBIN_DEST_MAPPED_ROOT" \
		"$l_mockbin_state_datasets" "$l_mockbin_state_dst_snaps" dataset \
		>"$l_mockbin_state_dir/dst_snapshots.list" || return 1

	# Mimic `zfs list -H <dataset>`: name, used, avail, refer, mountpoint.
	printf '%s\t96K\t1.0G\t24K\t/%s\n' "$ZXFER_MOCKBIN_DEST_MAPPED_ROOT" \
		"$ZXFER_MOCKBIN_DEST_MAPPED_ROOT" >"$l_mockbin_state_dir/dst_exists.list"

	{
		printf '%s\n' "$ZXFER_MOCKBIN_DEST_ROOT"
		printf '%s\n' "$ZXFER_MOCKBIN_DEST_MAPPED_ROOT"
		l_mockbin_state_index=1
		while [ "$l_mockbin_state_index" -le "$l_mockbin_state_datasets" ]; do
			printf '%s/child%d\n' "$ZXFER_MOCKBIN_DEST_MAPPED_ROOT" \
				"$l_mockbin_state_index"
			l_mockbin_state_index=$((l_mockbin_state_index + 1))
		done
	} >"$l_mockbin_state_dir/dst_datasets.list"

	# Per-dataset depth-1 snapshot listings answer the live recheck zxfer
	# issues immediately before each send/receive pair.
	l_mockbin_state_index=0
	while [ "$l_mockbin_state_index" -le "$l_mockbin_state_datasets" ]; do
		if [ "$l_mockbin_state_index" -eq 0 ]; then
			l_mockbin_state_dataset=$ZXFER_MOCKBIN_DEST_MAPPED_ROOT
		else
			l_mockbin_state_dataset="$ZXFER_MOCKBIN_DEST_MAPPED_ROOT/child$l_mockbin_state_index"
		fi
		awk -v dataset="$l_mockbin_state_dataset" -v d="$l_mockbin_state_index" \
			-v s="$l_mockbin_state_dst_snaps" 'BEGIN {
				for (i = 1; i <= s; i++)
					printf "%s@snap%d\t1%04d%05d%09d\n", dataset, i, d, i, 7
			}' >"$l_mockbin_state_dir/dst_d1_$l_mockbin_state_index.list" || return 1
		l_mockbin_state_index=$((l_mockbin_state_index + 1))
	done

	{
		printf '%s\t%s\t%s\n' \
			"list -Hr -o name,guid -s creation -t snapshot $ZXFER_MOCKBIN_SOURCE_ROOT" \
			src_snapshots.list 0
		printf '%s\t%s\t%s\n' \
			"list -H $ZXFER_MOCKBIN_DEST_MAPPED_ROOT" dst_exists.list 0
		printf '%s\t%s\t%s\n' \
			"list -Hr -o name,guid -t snapshot $ZXFER_MOCKBIN_DEST_MAPPED_ROOT" \
			dst_snapshots.list 0
		printf '%s\t%s\t%s\n' \
			"list -t filesystem,volume -Hr -o name $ZXFER_MOCKBIN_DEST_ROOT" \
			dst_datasets.list 0
		l_mockbin_state_index=0
		while [ "$l_mockbin_state_index" -le "$l_mockbin_state_datasets" ]; do
			if [ "$l_mockbin_state_index" -eq 0 ]; then
				l_mockbin_state_dataset=$ZXFER_MOCKBIN_DEST_MAPPED_ROOT
			else
				l_mockbin_state_dataset="$ZXFER_MOCKBIN_DEST_MAPPED_ROOT/child$l_mockbin_state_index"
			fi
			printf '%s\t%s\t%s\n' \
				"list -H -d 1 -o name,guid -t snapshot $l_mockbin_state_dataset" \
				"dst_d1_$l_mockbin_state_index.list" 0
			l_mockbin_state_index=$((l_mockbin_state_index + 1))
		done
	} >"$l_mockbin_state_dir/manifest"
}

# Purpose: Generate the deterministic dataset/snapshot fixture tree plus the
# manifests covering every discovery command shape the current ./zxfer
# issues for local recursive replication.
# Usage: zxfer_mockbin_build_fixture_tree <fixture-dir> <num-datasets>
# <snaps-per-dataset>. Source tree is srcpool/data with child1..childN and
# snap1..snapS each (root included). Builds two complete state dirs to use
# as MOCK_ZFS_FIXTURE_DIR:
#   <fixture-dir>/noop         destination identical to the source;
#   <fixture-dir>/incremental  every destination dataset missing the last
#                              snapshot (requires snaps-per-dataset >= 2).
zxfer_mockbin_build_fixture_tree() {
	l_mockbin_tree_root=$1
	l_mockbin_tree_datasets=$2
	l_mockbin_tree_snaps=$3

	case "$l_mockbin_tree_datasets" in
	'' | *[!0-9]*)
		printf 'zxfer_mockbin_build_fixture_tree: num-datasets must be a non-negative integer: %s\n' \
			"$l_mockbin_tree_datasets" >&2
		return 1
		;;
	esac
	case "$l_mockbin_tree_snaps" in
	'' | *[!0-9]* | 0 | 1)
		printf 'zxfer_mockbin_build_fixture_tree: snaps-per-dataset must be >= 2: %s\n' \
			"$l_mockbin_tree_snaps" >&2
		return 1
		;;
	esac

	zxfer_mockbin_write_fixture_state_dir "$l_mockbin_tree_root/noop" \
		"$l_mockbin_tree_datasets" "$l_mockbin_tree_snaps" \
		"$l_mockbin_tree_snaps" || return 1
	zxfer_mockbin_write_fixture_state_dir "$l_mockbin_tree_root/incremental" \
		"$l_mockbin_tree_datasets" "$l_mockbin_tree_snaps" \
		"$((l_mockbin_tree_snaps - 1))" || return 1
}

# Purpose: Print the ZXFER_SECURE_PATH value that resolves mocks first and
# everything else from the standard system directories.
# Usage: zxfer_mockbin_secure_path_env <mockdir> — pass the result as
# ZXFER_SECURE_PATH when invoking ./zxfer so the canned zfs and any counting
# wrappers shadow the system tools.
zxfer_mockbin_secure_path_env() {
	l_mockbin_secure_dir=$1

	printf '%s:%s\n' "$l_mockbin_secure_dir" "$ZXFER_MOCKBIN_SYSTEM_SECURE_PATH"
}

# Purpose: Run the real ./zxfer launcher black-box against a mock bin dir and
# one canned-zfs fixture state directory.
# Usage: zxfer_mockbin_run_zxfer <mockdir> <fixture-state-dir> <zfs-log>
# [zxfer-arg...]. Resolves the launcher from $ZXFER_MOCKBIN_ZXFER_BIN, then
# $ZXFER_ROOT/zxfer (set by tests/test_helper.sh). Refuses to run when the
# canned zfs is missing from <mockdir> so a misbuilt mock dir can never let
# zxfer resolve a real zfs. Stdout/stderr pass through; redirect at the call
# site. Returns zxfer's exit status.
# Side effects: Clears ZXFER_SOURCE_MODULES_THROUGH in the child environment.
# Suites that source tests/test_helper.sh leak it as an exported variable
# (assignments preceding the `.` special builtin persist exported in
# bash-as-sh), which would otherwise truncate the launcher's module sourcing.
zxfer_mockbin_run_zxfer() {
	l_mockbin_run_mockdir=$1
	l_mockbin_run_state=$2
	l_mockbin_run_log=$3
	shift 3

	l_mockbin_run_bin=${ZXFER_MOCKBIN_ZXFER_BIN:-${ZXFER_ROOT:-.}/zxfer}
	if [ ! -x "$l_mockbin_run_bin" ]; then
		printf 'zxfer_mockbin_run_zxfer: zxfer launcher not executable: %s\n' \
			"$l_mockbin_run_bin" >&2
		return 1
	fi
	if [ ! -x "$l_mockbin_run_mockdir/zfs" ]; then
		printf 'zxfer_mockbin_run_zxfer: canned zfs missing in %s; refusing to run zxfer\n' \
			"$l_mockbin_run_mockdir" >&2
		return 1
	fi

	MOCK_ZFS_LOG="$l_mockbin_run_log" \
		MOCK_ZFS_FIXTURE_DIR="$l_mockbin_run_state" \
		ZXFER_SECURE_PATH=$(zxfer_mockbin_secure_path_env "$l_mockbin_run_mockdir") \
		ZXFER_SECURE_PATH_APPEND="" \
		ZXFER_SOURCE_MODULES_THROUGH="" \
		"$l_mockbin_run_bin" "$@"
}
