#!/bin/sh
#
# Stable shunit2 entry point for snapshot producers, remote discovery batches,
# and snapshot-discovery orchestration behavior.
#
# Test definitions live in ordered behavior fragments below. Keep the fragment
# markers aligned with the source order so --list-tests and shunit2 execute the
# same registered-test contract.
#
# shellcheck disable=SC1090,SC2030,SC2031,SC2034,SC2154,SC2317,SC2329

TESTS_DIR=$(dirname "$0")

# shellcheck source=tests/test_helper.sh
. "$TESTS_DIR/test_helper.sh"

zxfer_source_runtime_modules_through "zxfer_snapshot_discovery.sh"

# shellcheck source=tests/fixtures/snapshot_discovery/fixture.sh
. "$TESTS_DIR/fixtures/snapshot_discovery/fixture.sh"

# zxfer-test-fragment: fixtures/snapshot_discovery/source_producer_cases.sh
# shellcheck source=tests/fixtures/snapshot_discovery/source_producer_cases.sh
. "$TESTS_DIR/fixtures/snapshot_discovery/source_producer_cases.sh"

# zxfer-test-fragment: fixtures/snapshot_discovery/snapshot_stream_cases.sh
# shellcheck source=tests/fixtures/snapshot_discovery/snapshot_stream_cases.sh
. "$TESTS_DIR/fixtures/snapshot_discovery/snapshot_stream_cases.sh"

# zxfer-test-fragment: fixtures/snapshot_discovery/full_discovery_cases.sh
# shellcheck source=tests/fixtures/snapshot_discovery/full_discovery_cases.sh
. "$TESTS_DIR/fixtures/snapshot_discovery/full_discovery_cases.sh"

# zxfer-test-fragment: fixtures/snapshot_discovery/remote_batch_cases.sh
# shellcheck source=tests/fixtures/snapshot_discovery/remote_batch_cases.sh
. "$TESTS_DIR/fixtures/snapshot_discovery/remote_batch_cases.sh"

# zxfer-test-fragment: fixtures/snapshot_discovery/dry_run_failure_cases.sh
# shellcheck source=tests/fixtures/snapshot_discovery/dry_run_failure_cases.sh
. "$TESTS_DIR/fixtures/snapshot_discovery/dry_run_failure_cases.sh"

zxfer_test_add_snapshot_discovery_source_producer_cases() {
	suite_addTest test_zxfer_reset_snapshot_discovery_state_preserves_remote_parallel_state
	suite_addTest test_zxfer_reset_snapshot_discovery_state_preserves_remote_parallel_reuse_across_discovery_passes
	suite_addTest test_zxfer_limit_snapshot_discovery_capture_lines_defaults_invalid_limits_in_current_shell
	suite_addTest test_destination_snapshot_dataset_helpers_map_root_and_child_datasets
	suite_addTest test_destination_snapshot_dataset_helpers_cover_exact_root_and_fallback_mappings
	suite_addTest test_destination_snapshot_dataset_helpers_treat_regex_significant_source_names_as_literal_paths
	suite_addTest test_build_source_snapshot_list_cmd_reports_parallel_helper_failures_in_current_shell
	suite_addTest test_ensure_parallel_available_for_source_jobs_requires_local_parallel
	suite_addTest test_ensure_parallel_available_for_source_jobs_trusts_available_local_parallel
	suite_addTest test_ensure_parallel_available_for_source_jobs_reports_missing_remote_parallel_in_current_shell
	suite_addTest test_ensure_parallel_available_for_source_jobs_returns_success_when_parallel_is_not_requested
	suite_addTest test_ensure_parallel_available_for_source_jobs_skips_local_parallel_for_remote_runs
	suite_addTest test_ensure_parallel_available_for_source_jobs_accepts_resolved_remote_parallel_after_resolution
	suite_addTest test_ensure_parallel_available_for_source_jobs_reuses_cached_remote_parallel_path_for_same_host_and_path
	suite_addTest test_ensure_parallel_available_for_source_jobs_trusts_resolved_remote_parallel_without_banner_probe
	suite_addTest test_ensure_parallel_available_for_source_jobs_preserves_remote_parallel_resolution_failures
	suite_addTest test_ensure_parallel_available_for_source_jobs_refreshes_remote_parallel_path_when_origin_host_changes
	suite_addTest test_build_source_snapshot_list_cmd_fails_closed_when_local_parallel_is_unavailable
	suite_addTest test_build_source_snapshot_list_cmd_uses_serial_local_discovery_when_parallel_jobs_are_disabled
	suite_addTest test_build_source_snapshot_list_cmd_preserves_serial_render_status
	suite_addTest test_build_source_snapshot_list_cmd_uses_parallel_local_discovery_directly
	suite_addTest test_build_source_snapshot_list_cmd_guards_local_parallel_discovery_with_sentinel
	suite_addTest test_build_source_snapshot_list_cmd_guards_remote_parallel_discovery_with_sentinel
	suite_addTest test_build_source_snapshot_name_list_cmd_guards_compressed_remote_listing_with_sentinel
	suite_addTest test_local_parallel_discovery_pipeline_strips_sentinel_on_success
	suite_addTest test_local_parallel_discovery_pipeline_fails_when_sub_listing_fails
	suite_addTest test_local_parallel_discovery_pipeline_fails_when_enumeration_fails
	suite_addTest test_build_source_snapshot_list_cmd_preserves_local_parallel_builder_statuses
	suite_addTest test_build_source_snapshot_list_cmd_uses_parallel_remote_discovery_with_metadata_compression
	suite_addTest test_get_origin_metadata_compress_safe_uses_configured_default_for_snapshot_metadata
	suite_addTest test_get_origin_metadata_compress_safe_covers_disabled_and_custom_resolution
	suite_addTest test_build_source_snapshot_name_list_cmd_covers_local_and_remote_rendering
	suite_addTest test_build_source_snapshot_name_list_cmd_covers_current_shell_success_paths
	suite_addTest test_build_source_snapshot_name_list_cmd_keeps_source_side_excludes_local_when_jobs_are_configured
	suite_addTest test_build_source_snapshot_name_list_cmd_preserves_render_failures
	suite_addTest test_build_source_snapshot_name_list_cmd_does_not_require_remote_awk_for_excludes
	suite_addTest test_build_source_snapshot_name_list_cmd_does_not_probe_parallel_before_work_is_proven
	suite_addTest test_build_source_snapshot_name_list_cmd_preserves_local_recursive_render_failures_when_jobs_requested
	suite_addTest test_build_source_snapshot_list_cmd_fails_closed_when_remote_parallel_is_unavailable
	suite_addTest test_build_source_snapshot_list_cmd_preserves_remote_ssh_wrapper_status
	suite_addTest test_build_source_snapshot_list_cmd_preserves_remote_parallel_builder_statuses
	suite_addTest test_build_source_snapshot_list_cmd_preserves_local_parallel_dataset_input_render_failure
	suite_addTest test_write_source_snapshot_list_to_file_uses_direct_background_runner_when_serial
	suite_addTest test_write_source_snapshot_list_to_file_tracks_profile_counters_when_very_verbose
	suite_addTest test_write_source_snapshot_list_to_file_tracks_remote_ssh_profile_counter_when_very_verbose
	suite_addTest test_write_source_snapshot_list_to_file_backgrounds_parallel_command
	suite_addTest test_write_source_snapshot_list_to_file_uses_current_shell_temp_file_result
	suite_addTest test_write_source_snapshot_list_to_file_uses_current_shell_read_scratch
	suite_addTest test_write_source_snapshot_list_to_file_reports_staged_command_read_failures_after_build_failure
	suite_addTest test_write_source_snapshot_list_to_file_trims_staged_build_failure_newline
	suite_addTest test_write_source_snapshot_list_to_file_reports_staged_command_read_failures_after_build_success
	suite_addTest test_write_source_snapshot_list_to_file_skips_execution_in_dry_run
	suite_addTest test_write_source_snapshot_list_to_file_reports_preview_render_failures_in_dry_run
	suite_addTest test_write_source_snapshot_list_to_file_preserves_outfile_stage_failures_in_dry_run
	suite_addTest test_write_source_snapshot_list_to_file_preserves_errfile_stage_failures_in_dry_run
	suite_addTest test_write_source_snapshot_list_to_file_stages_sorted_sidecar_in_dry_run_when_requested
	suite_addTest test_write_source_snapshot_list_to_file_reports_sorted_sidecar_temp_failures_in_dry_run
	suite_addTest test_write_source_snapshot_list_to_file_preserves_background_sort_setup_failures
	suite_addTest test_write_source_snapshot_list_to_file_preserves_background_sort_temp_failures
	suite_addTest test_write_source_snapshot_list_to_file_preserves_direct_background_execution_failures
	suite_addTest test_write_source_snapshot_list_to_file_runs_serial_builder_output_when_jobs_remain_configured
	suite_addTest test_write_source_snapshot_list_to_file_can_sort_inside_background_job
	suite_addTest test_write_source_snapshot_list_to_file_preserves_source_failure_when_streaming_background_sort
	suite_addTest test_execute_source_snapshot_list_background_cmd_with_sort_delegates_when_no_sorted_file_requested
	suite_addTest test_execute_source_snapshot_list_background_cmd_with_sort_preserves_setup_failures
	suite_addTest test_execute_source_snapshot_list_background_cmd_with_sort_aborts_child_when_registration_fails
	suite_addTest test_execute_source_snapshot_name_list_background_sort_cmd_runs_without_error_file
	suite_addTest test_execute_source_snapshot_name_list_background_sort_cmd_filters_excluded_snapshots_before_sort
	suite_addTest test_execute_source_snapshot_name_list_background_sort_cmd_preserves_setup_failures
	suite_addTest test_execute_source_snapshot_name_list_background_sort_cmd_aborts_child_when_registration_fails
}

zxfer_test_add_snapshot_discovery_snapshot_stream_cases() {
	suite_addTest test_write_snapshot_delta_files_splits_both_diff_directions
	suite_addTest test_write_snapshot_delta_files_preserves_tempfile_failures
	suite_addTest test_write_snapshot_delta_files_preserves_source_stage_failures
	suite_addTest test_write_snapshot_delta_files_preserves_destination_stage_failures
	suite_addTest test_write_snapshot_delta_files_preserves_splitter_failures
	suite_addTest test_reverse_file_lines_uses_linear_reverse_for_small_inputs
	suite_addTest test_reverse_file_lines_falls_back_to_sort_for_large_inputs
	suite_addTest test_zxfer_should_use_linear_reverse_for_file_rejects_non_numeric_threshold
	suite_addTest test_zxfer_should_use_linear_reverse_for_file_preserves_line_count_failures
	suite_addTest test_zxfer_should_use_linear_reverse_for_file_rejects_malformed_line_counts
	suite_addTest test_zxfer_reverse_plain_file_lines_with_sort_reports_tempfile_allocation_failures
	suite_addTest test_zxfer_reverse_plain_file_lines_with_sort_returns_failure_when_numbering_fails
	suite_addTest test_zxfer_reverse_plain_file_lines_with_sort_uses_current_shell_temp_file_result
	suite_addTest test_set_g_recursive_source_list_applies_exclude_filter_and_verbose_output
	suite_addTest test_set_g_recursive_source_list_accepts_leading_dash_exclude_patterns
	suite_addTest test_set_g_recursive_source_list_filters_excluded_snapshots_before_noop_compare
	suite_addTest test_write_destination_snapshot_list_to_files_outputs_empty_when_destination_missing
	suite_addTest test_write_destination_snapshot_list_to_files_reports_destination_probe_failures
	suite_addTest test_write_destination_snapshot_list_to_files_reports_snapshot_listing_failures
	suite_addTest test_write_destination_snapshot_list_to_files_reports_empty_stage_failures_when_destination_missing
	suite_addTest test_write_destination_snapshot_list_to_files_uses_destination_root_for_trailing_slash_sources
	suite_addTest test_set_g_recursive_source_list_treats_trailing_slash_rewritten_destination_snapshots_as_common
	suite_addTest test_start_destination_snapshot_name_sorted_fifo_producer_streams_statuses_and_handles_registration_failures
	suite_addTest test_abort_fast_noop_background_pid_covers_invalid_and_fallback_paths
	suite_addTest test_normalize_destination_snapshot_list_rewrites_trailing_slash_destination_to_source_paths
	suite_addTest test_normalize_destination_snapshot_list_treats_temp_paths_as_literal
	suite_addTest test_normalize_destination_snapshot_list_rewrites_only_leading_destination_prefix
	suite_addTest test_normalize_destination_snapshot_list_does_not_rewrite_similar_dataset_prefixes
	suite_addTest test_normalize_destination_snapshot_list_preserves_status_tempfile_failures
	suite_addTest test_normalize_destination_snapshot_list_preserves_awk_failures
	suite_addTest test_normalize_destination_snapshot_stream_for_noop_proof_rewrites_and_filters
	suite_addTest test_normalize_destination_snapshot_stream_for_noop_proof_handles_trailing_slash_streams
	suite_addTest test_filter_snapshot_file_with_excludes_filters_by_snapshot_dataset
	suite_addTest test_filter_snapshot_file_with_excludes_handles_comm_destination_rows
	suite_addTest test_filter_snapshot_file_with_excludes_copies_input_without_patterns
	suite_addTest test_snapshot_discovery_need_helpers_cover_recursive_shortcuts
	suite_addTest test_set_g_recursive_source_list_logs_when_no_new_snapshots_exist
	suite_addTest test_set_g_recursive_source_list_uses_existing_presorted_source_sidecar
	suite_addTest test_set_g_recursive_source_list_reports_missing_presorted_source_sidecar
	suite_addTest test_set_g_recursive_source_list_tracks_destination_only_snapshot_datasets
	suite_addTest test_set_g_recursive_source_list_queues_name_identical_guid_divergence_from_initial_records
	suite_addTest test_set_g_recursive_source_list_verbose_summarizes_dirty_recursive_delta
	suite_addTest test_set_g_recursive_source_list_treats_tmpdir_derived_paths_as_literal
	suite_addTest test_set_g_recursive_source_list_reports_recursive_snapshot_diff_failures
	suite_addTest test_set_g_recursive_source_list_reports_recursive_source_dataset_transfer_awk_failures
	suite_addTest test_set_g_recursive_source_list_reports_recursive_destination_dataset_delete_awk_failures
	suite_addTest test_set_g_recursive_source_list_reports_recursive_source_dataset_inventory_failures
	suite_addTest test_set_g_recursive_source_list_reports_recursive_source_dataset_inventory_awk_failures
	suite_addTest test_set_g_recursive_source_list_reports_invalid_exclude_pattern_failures
	suite_addTest test_set_g_recursive_source_list_fuzzes_tmpdir_derived_paths_with_odd_characters
}

zxfer_test_add_snapshot_discovery_full_discovery_cases() {
	suite_addTest test_get_zfs_list_bootstraps_missing_destination_dataset_when_pool_exists
	suite_addTest test_get_zfs_list_bootstraps_missing_destination_dataset_when_omnios_reports_no_such_pool_or_dataset
	suite_addTest test_get_zfs_list_reports_pool_lookup_failure_when_destination_root_has_no_slash
	suite_addTest test_publish_destination_dataset_inventory_bootstraps_rootless_missing_destination
	suite_addTest test_collect_local_destination_dataset_inventory_preserves_setup_and_publish_failures
	suite_addTest test_get_zfs_list_seeds_destination_existence_cache_from_recursive_dataset_list
	suite_addTest test_get_zfs_list_reports_destination_inventory_readback_failures
	suite_addTest test_get_zfs_list_reports_destination_inventory_stderr_readback_failures
	suite_addTest test_get_zfs_list_reports_empty_destination_inventory_readbacks
	suite_addTest test_get_zfs_list_reports_destination_snapshot_list_readback_failures
	suite_addTest test_get_zfs_list_reports_source_snapshot_list_readback_failures
	suite_addTest test_get_zfs_list_preserves_source_snapshot_record_cache_tempfile_failures
	suite_addTest test_get_zfs_list_reports_source_snapshot_record_cache_stage_failures
	suite_addTest test_get_zfs_list_skips_snapshot_record_caches_for_recursive_noop_without_later_work
	suite_addTest test_get_zfs_list_fast_remote_recursive_noop_skips_creation_order_discovery
	suite_addTest test_get_zfs_list_fast_remote_recursive_noop_allows_noop_safe_property_and_delete_flags
	suite_addTest test_get_zfs_list_fast_remote_recursive_noop_shortcuts_exact_match_without_exclude_filter
	suite_addTest test_get_zfs_list_fast_remote_recursive_noop_falls_back_when_snapshot_names_differ
	suite_addTest test_get_zfs_list_fast_remote_recursive_noop_falls_back_when_snapshot_guids_differ
	suite_addTest test_get_zfs_list_fast_remote_recursive_noop_falls_back_when_excludes_filter_all_source_snapshots
	suite_addTest test_fast_recursive_noop_discovery_eligibility_gates
	suite_addTest test_try_fast_recursive_noop_discovery_records_parallel_source_profile_counter
	suite_addTest test_try_fast_recursive_noop_discovery_preserves_setup_failures
	suite_addTest test_try_fast_recursive_noop_discovery_reports_source_failures
	suite_addTest test_try_fast_recursive_noop_discovery_reports_destination_fifo_status_failures
	suite_addTest test_try_fast_recursive_noop_discovery_reports_compare_failures
	suite_addTest test_get_zfs_list_preserves_fast_noop_hard_failure_status
	suite_addTest test_get_zfs_list_stages_file_backed_snapshot_record_lookups
}

zxfer_test_add_snapshot_discovery_remote_batch_cases() {
	suite_addTest test_get_zfs_list_remote_target_batches_destination_discovery
	suite_addTest test_build_remote_destination_discovery_batch_script_matches_golden_output
	suite_addTest test_build_remote_destination_discovery_batch_script_preserves_dependency_path_failures
	suite_addTest test_build_remote_destination_discovery_batch_script_streams_snapshot_stdout_directly
	suite_addTest test_destination_discovery_batch_status_loader_rejects_malformed_sidecars
	suite_addTest test_destination_discovery_batch_status_loader_accepts_complete_sidecars
	suite_addTest test_read_snapshot_discovery_status_file_defaults_empty_sidecars
	suite_addTest test_get_zfs_list_remote_target_batches_missing_destination_root_fallback
	suite_addTest test_get_zfs_list_remote_target_batches_inventory_failures
	suite_addTest test_get_zfs_list_remote_target_transport_failures_preserve_diagnostic_and_status
	suite_addTest test_remote_destination_failure_staging_preserves_original_status_and_diagnostic
	suite_addTest test_get_zfs_list_remote_target_batches_snapshot_failures
	suite_addTest test_get_zfs_list_remote_target_batches_malformed_payloads_fail_closed
	suite_addTest test_run_remote_destination_discovery_batch_preserves_setup_and_transport_failures
	suite_addTest test_prepare_remote_destination_discovery_batch_preserves_rootless_pool_and_wrapper_status
	suite_addTest test_run_remote_destination_discovery_batch_preserves_transport_sidecar_read_failures
	suite_addTest test_run_remote_destination_discovery_batch_uses_one_workspace_and_one_ssh
	suite_addTest test_run_remote_destination_discovery_batch_rejects_truncated_and_reordered_protocols
	suite_addTest test_run_remote_destination_discovery_batch_preserves_stage_and_readback_failures
	suite_addTest test_run_remote_destination_discovery_batch_rolls_back_late_publish_failures
	suite_addTest test_remote_destination_discovery_transaction_restores_partial_backup
	suite_addTest test_remote_destination_discovery_transaction_clears_all_targets_when_rollback_fails
	suite_addTest test_remote_destination_discovery_workspace_rejects_untrusted_publish_targets
	suite_addTest test_prepare_remote_destination_discovery_batch_preserves_transport_token_failure_after_reporting
	suite_addTest test_remote_destination_discovery_publish_target_rejects_reserved_workspace_names
	suite_addTest test_load_remote_destination_discovery_transport_status_rejects_nonnumeric_content
	suite_addTest test_restore_remote_destination_discovery_publish_targets_reports_each_partial_move_failure
	suite_addTest test_clear_remote_destination_discovery_publish_targets_reports_clear_failure
	suite_addTest test_publish_remote_destination_discovery_workspace_clears_after_backup_restore_failure
	suite_addTest test_process_remote_destination_discovery_workspace_classifies_status_loader_failure
	suite_addTest test_report_remote_destination_discovery_failure_handles_malformed_and_unknown_kinds
	suite_addTest test_get_zfs_list_local_destination_discovery_does_not_use_remote_batch
	suite_addTest test_get_zfs_list_tracks_stage_timings_when_very_verbose
	suite_addTest test_get_zfs_list_throws_when_source_snapshot_list_is_empty
	suite_addTest test_get_zfs_list_restores_source_last_command_when_background_snapshot_listing_fails
	suite_addTest test_get_zfs_list_reports_generic_source_failure_when_background_snapshot_listing_has_no_stderr
	suite_addTest test_get_zfs_list_reports_supervisor_completion_failures_before_source_stderr_handling
	suite_addTest test_get_zfs_list_reports_supervisor_queue_publish_failures_before_source_stderr_handling
	suite_addTest test_get_zfs_list_reports_source_stderr_readback_failures_after_background_failure
}

zxfer_test_add_snapshot_discovery_dry_run_failure_cases() {
	suite_addTest test_write_destination_snapshot_list_to_files_skips_live_validation_in_dry_run
	suite_addTest test_write_destination_snapshot_list_to_files_reports_preview_render_failures_in_dry_run
	suite_addTest test_write_destination_snapshot_list_to_files_preserves_record_stage_failures_in_dry_run
	suite_addTest test_write_destination_snapshot_list_to_files_preserves_sorted_stage_failures_in_dry_run
	suite_addTest test_get_zfs_list_skips_live_snapshot_discovery_in_dry_run
	suite_addTest test_get_zfs_list_dry_run_ignores_stale_background_completion_failure_state
	suite_addTest test_zxfer_read_snapshot_discovery_capture_file_reads_multiline_results_in_current_shell
	suite_addTest test_zxfer_read_snapshot_discovery_capture_file_fails_closed_on_redirection_errors_in_current_shell
	suite_addTest test_zxfer_check_parallel_source_jobs_in_current_shell_preserves_nested_validation_status_without_tempfile_staging
	suite_addTest test_zxfer_check_parallel_source_jobs_in_current_shell_preserves_current_shell_reason_when_nested_validation_reuses_generic_scratch
	suite_addTest test_zxfer_check_parallel_source_jobs_in_current_shell_avoids_tempfile_allocation_and_cleanup
	suite_addTest test_build_source_snapshot_list_cmd_preserves_remote_parallel_resolution_from_current_shell
	suite_addTest test_capture_recursive_dataset_list_from_lines_file_sorts_unique_entries_in_current_shell
	suite_addTest test_capture_recursive_dataset_list_from_lines_file_reports_tempfile_failures
	suite_addTest test_capture_recursive_dataset_list_from_lines_file_reports_staged_read_failures
	suite_addTest test_capture_recursive_dataset_list_from_snapshot_file_extracts_sorted_unique_datasets
	suite_addTest test_capture_recursive_dataset_list_from_snapshot_file_reports_line_capture_failures
	suite_addTest test_filter_recursive_dataset_list_with_excludes_passthrough_without_patterns_in_current_shell
	suite_addTest test_filter_recursive_dataset_list_with_excludes_filters_matching_entries_in_current_shell
	suite_addTest test_filter_recursive_dataset_list_with_excludes_reports_second_tempfile_failures
	suite_addTest test_filter_recursive_dataset_list_with_excludes_reports_staged_read_failures
	suite_addTest test_write_source_snapshot_list_to_file_reports_tempfile_failures
	suite_addTest test_capture_recursive_dataset_list_from_snapshot_file_reports_tempfile_failures
	suite_addTest test_filter_recursive_dataset_list_with_excludes_reports_initial_tempfile_failures
	suite_addTest test_filter_recursive_dataset_list_with_excludes_reports_input_write_failures
	suite_addTest test_set_g_recursive_source_list_reports_source_sort_failures
	suite_addTest test_set_g_recursive_source_list_reports_recursive_delete_diff_failures
	suite_addTest test_set_g_recursive_source_list_reports_recursive_destination_exclude_failures
	suite_addTest test_set_g_recursive_source_list_reports_recursive_source_inventory_exclude_failures
	suite_addTest test_set_g_recursive_source_list_reports_destination_snapshot_exclude_filter_failures
	suite_addTest test_set_g_recursive_source_list_reports_empty_source_delta_stage_failures
	suite_addTest test_set_g_recursive_source_list_reports_empty_destination_delta_stage_failures
	suite_addTest test_set_g_recursive_source_list_reports_snapshot_compare_failures
	suite_addTest test_recursive_snapshot_delta_stage_helpers_preserve_failure_statuses_when_reporter_returns
	suite_addTest test_filter_recursive_dataset_list_with_excludes_preserves_grep_hard_failures
	suite_addTest test_execute_source_snapshot_name_list_background_sort_cmd_preserves_count_file_quoting_failures
	suite_addTest test_execute_source_snapshot_name_list_background_sort_cmd_preserves_count_status_tempfile_failures
	suite_addTest test_execute_source_snapshot_name_list_background_sort_cmd_preserves_count_status_quoting_failures
	suite_addTest test_execute_source_snapshot_name_list_background_sort_cmd_preserves_filter_status_quoting_failures
	suite_addTest test_get_zfs_list_reports_initial_tempfile_failures
	suite_addTest test_get_zfs_list_reports_second_source_tempfile_failures
	suite_addTest test_get_zfs_list_reports_destination_list_tempfile_failures
	suite_addTest test_get_zfs_list_reports_destination_list_errfile_tempfile_failures
	suite_addTest test_get_zfs_list_propagates_recursive_source_list_failures
	suite_addTest test_collapsed_status_ladder_forms_preserve_original_failure_status
}

suite() {
	zxfer_test_add_snapshot_discovery_source_producer_cases
	zxfer_test_add_snapshot_discovery_snapshot_stream_cases
	zxfer_test_add_snapshot_discovery_full_discovery_cases
	zxfer_test_add_snapshot_discovery_remote_batch_cases
	zxfer_test_add_snapshot_discovery_dry_run_failure_cases
}

# shellcheck source=tests/shunit2/shunit2
. "$SHUNIT2_BIN"
