#!/bin/sh
#
# Stable shunit2 entry point for replication setup, snapshot transfer,
# orchestration, ready-queue, and failure-path behavior.
#
# Test definitions live in ordered behavior fragments below. Keep the fragment
# markers and static registrars aligned so listing and execution preserve the
# 161-test contract.
#
# shellcheck disable=SC1090,SC2030,SC2031,SC2034,SC2317,SC2329

TESTS_DIR=$(dirname "$0")

# shellcheck source=tests/test_helper.sh
. "$TESTS_DIR/test_helper.sh"
# Replication orchestration fixtures render property-backup metadata.
# shellcheck source=tests/helpers/backup_fixtures.sh
. "$TESTS_DIR/helpers/backup_fixtures.sh"

zxfer_source_runtime_modules_through "zxfer_replication.sh"

zxfer_get_zfs_list() {
	STUB_ZFS_LIST_CALLS=$((STUB_ZFS_LIST_CALLS + 1))
}

zxfer_stopsvcs() {
	cat >>"$STUB_STOPSVCS_LOG"
}

zxfer_newsnap() {
	printf '%s\n' "$1" >>"$STUB_NEW_SNAP_LOG"
}

zxfer_wait_for_zfs_send_jobs() {
	:
}

mock_zfs_tool() {
	printf '%s\n' "$*" >>"$STUB_ZFS_CMD_LOG"
}

zxfer_run_source_zfs_cmd() {
	if [ "$1" = "get" ] && [ "$2" = "-Ho" ] && [ "$3" = "value" ] && [ "$4" = "mounted" ]; then
		# Simulate a mounted filesystem so migration preflight passes.
		printf 'yes\n'
		return 0
	fi

	if [ "$1" = "unmount" ]; then
		printf 'unmount %s\n' "$2" >>"$STUB_ZFS_CMD_LOG"
		return 0
	fi

	mock_zfs_tool "$@"
}

oneTimeSetUp() {
	zxfer_test_create_tmpdir "zxfer_replication"
}

oneTimeTearDown() {
	zxfer_test_cleanup_tmpdir
}

# Reset per-test replication logs and destination-existence cache.
zxfer_test_reset_replication_log_fixture() {
	: >"$TEST_TMPDIR/zxfer_stopsvcs.log"
	: >"$TEST_TMPDIR/zxfer_newsnap.log"
	: >"$TEST_TMPDIR/zfs_cmd.log"
	unset ZXFER_BACKUP_DIR
	STUB_STOPSVCS_LOG="$TEST_TMPDIR/zxfer_stopsvcs.log"
	STUB_NEW_SNAP_LOG="$TEST_TMPDIR/zxfer_newsnap.log"
	STUB_ZFS_CMD_LOG="$TEST_TMPDIR/zfs_cmd.log"
	STUB_ZFS_LIST_CALLS=0
	zxfer_reset_destination_existence_cache
}

# Restore the replication command stubs that tests may override.
zxfer_test_reset_replication_command_fixture() {
	zxfer_get_zfs_list() {
		STUB_ZFS_LIST_CALLS=$((STUB_ZFS_LIST_CALLS + 1))
	}
	zxfer_stopsvcs() {
		cat >>"$STUB_STOPSVCS_LOG"
	}
	zxfer_newsnap() {
		printf '%s\n' "$1" >>"$STUB_NEW_SNAP_LOG"
	}
	zxfer_wait_for_zfs_send_jobs() {
		:
	}
	mock_zfs_tool() {
		printf '%s\n' "$*" >>"$STUB_ZFS_CMD_LOG"
	}
	zxfer_run_source_zfs_cmd() {
		if [ "$1" = "get" ] && [ "$2" = "-Ho" ] && [ "$3" = "value" ] && [ "$4" = "mounted" ]; then
			printf 'yes\n'
			return 0
		fi

		if [ "$1" = "unmount" ]; then
			printf 'unmount %s\n' "$2" >>"$STUB_ZFS_CMD_LOG"
			return 0
		fi

		mock_zfs_tool "$@"
	}

}

# Reset parsed replication options and the destination root.
zxfer_test_reset_replication_option_fixture() {
	g_option_R_recursive=""
	g_option_N_nonrecursive=""
	g_option_n_dryrun=0
	g_option_v_verbose=0
	g_option_V_very_verbose=0
	g_option_j_jobs=1
	g_option_s_make_snapshot=0
	g_option_m_migrate=0
	g_option_c_services=""
	g_option_d_delete_destination_snapshots=0
	g_option_F_force_rollback=""
	g_option_P_transfer_property=0
	g_option_k_backup_property_mode=0
	g_option_o_override_property=""
	g_destination="backup/target"
}

# Reset source, destination, and live-view state for one iteration.
zxfer_test_reset_replication_dataset_fixture() {
	g_initial_source_had_trailing_slash=0
	g_initial_source=""
	g_recursive_source_list=""
	g_recursive_source_dataset_list=""
	g_recursive_destination_extra_dataset_list=""
	g_recursive_dest_list=""
	g_zxfer_source_snapshot_record_cache_file=""
	g_zxfer_destination_snapshot_record_cache_file=""
	g_zxfer_destination_mutation_generation=0
	g_zxfer_live_destination_view_generation=""
	g_zxfer_live_destination_view_root=""
	g_zxfer_live_destination_view_file=""
	g_zxfer_live_destination_view_serves_current_dataset=0
	g_did_delete_dest_snapshots=0
	g_last_common_snap=""
	g_dest_has_snapshots=0
	g_src_snapshot_transfer_list=""
	g_actual_dest=""
}

# Reset backup, iteration, snapshot, and yield scratch state.
zxfer_test_reset_replication_work_fixture() {
	g_backup_storage_root="$TEST_TMPDIR/backup_store"
	g_backup_file_contents=""
	g_pending_backup_file_contents=""
	g_zxfer_post_seed_property_sources_result=""
	g_zxfer_replication_iteration_list_result=""
	g_zxfer_replication_file_read_result=""
	g_zxfer_new_snapshot_name="zxfer_test_snapshot"
	g_zxfer_source_pvs_raw=""
	ZXFER_BASE_READONLY_PROPERTIES="type,mountpoint,creation"
	g_LZFS="mock_zfs_tool"
	stub_dest_created_by_zxfer=0
	g_dest_seed_requires_property_reconcile=0
	g_test_max_yield_iterations=8
	zxfer_get_max_yield_iterations() {
		printf '%s\n' "$g_test_max_yield_iterations"
	}
}

setUp() {
	zxfer_test_reset_replication_log_fixture
	zxfer_test_reset_replication_command_fixture
	zxfer_test_reset_replication_option_fixture
	zxfer_test_reset_replication_dataset_fixture
	zxfer_test_reset_replication_work_fixture
}

# Behavior-focused fragments keep the stable suite entry point while bounding
# the amount of replication test code a contributor must load at once.
# zxfer-test-fragment: suites/zxfer_replication_setup_migration_tests.sh
# shellcheck source=tests/suites/zxfer_replication_setup_migration_tests.sh
. "$TESTS_DIR/suites/zxfer_replication_setup_migration_tests.sh"

# zxfer-test-fragment: suites/zxfer_replication_snapshot_transfer_tests.sh
# shellcheck source=tests/suites/zxfer_replication_snapshot_transfer_tests.sh
. "$TESTS_DIR/suites/zxfer_replication_snapshot_transfer_tests.sh"

# zxfer-test-fragment: suites/zxfer_replication_orchestration_tests.sh
# shellcheck source=tests/suites/zxfer_replication_orchestration_tests.sh
. "$TESTS_DIR/suites/zxfer_replication_orchestration_tests.sh"

# zxfer-test-fragment: suites/zxfer_replication_queue_failure_tests.sh
# shellcheck source=tests/suites/zxfer_replication_queue_failure_tests.sh
. "$TESTS_DIR/suites/zxfer_replication_queue_failure_tests.sh"

zxfer_test_add_replication_setup_migration_tests() {
	suite_addTest test_resolve_initial_source_prefers_recursive_flag
	suite_addTest test_resolve_initial_source_uses_nonrecursive_when_only_N_set
	suite_addTest test_resolve_initial_source_conflicts_trigger_usage_error
	suite_addTest test_validate_zfs_mode_preconditions_rejects_services_without_svcadm
	suite_addTest test_resolve_initial_source_requires_N_or_R
	suite_addTest test_normalize_source_destination_strips_trailing_slashes
	suite_addTest test_normalize_source_destination_rejects_absolute_paths
	suite_addTest test_zxfer_read_replication_stage_file_preserves_runtime_readback_failures
	suite_addTest test_current_destination_is_initial_source_dataset_matches_resolved_destination
	suite_addTest test_current_destination_is_initial_source_dataset_fails_closed_when_resolution_fails
	suite_addTest test_rollback_destination_to_last_common_snapshot_shortcuts_non_destructive_cases_in_current_shell
	suite_addTest test_set_actual_dest_without_trailing_slash_appends_relative_path
	suite_addTest test_set_actual_dest_with_trailing_slash_preserves_destination_prefix
	suite_addTest test_set_actual_dest_treats_regex_significant_source_names_as_literal_paths
	suite_addTest test_refresh_dataset_iteration_state_populates_recursive_list_when_not_recursive
	suite_addTest test_refresh_dataset_iteration_state_preserves_list_when_recursive_mode_set
	suite_addTest test_refresh_dataset_iteration_state_refreshes_property_tree_prefetch_context_when_available
	suite_addTest test_maybe_capture_preflight_snapshot_captures_when_enabled
	suite_addTest test_maybe_capture_preflight_snapshot_dry_run_skips_refresh
	suite_addTest test_maybe_capture_preflight_snapshot_skips_when_migrating
	suite_addTest test_prepare_migration_services_stops_services_and_unmounts_sources
	suite_addTest test_prepare_migration_services_dry_run_previews_without_mutating_state
	suite_addTest test_prepare_migration_services_dry_run_uses_mountpoint_free_effective_readonly_list
	suite_addTest test_prepare_migration_services_preserves_service_restart_state_in_current_shell
	suite_addTest test_prepare_migration_services_passes_multiline_service_input_to_stopsvcs_in_current_shell
	suite_addTest test_prepare_migration_services_propagates_service_disable_failures
	suite_addTest test_stopsvcs_disables_services_and_tracks_restart_state
	suite_addTest test_stopsvcs_returns_when_no_services_are_provided
	suite_addTest test_stopsvcs_ignores_whitespace_only_service_input
	suite_addTest test_stopsvcs_relaunches_and_errors_when_disable_fails
	suite_addTest test_stopsvcs_normalizes_multiline_service_input_in_current_shell
	suite_addTest test_relaunch_enables_services_and_clears_need_flag
	suite_addTest test_relaunch_preserves_smf_patterns_without_pathname_or_ifs_expansion
	suite_addTest test_relaunch_returns_success_when_no_services_are_pending_in_current_shell
	suite_addTest test_relaunch_throws_when_service_enable_fails
	suite_addTest test_relaunch_continues_after_failures_and_keeps_only_failed_services_pending
	suite_addTest test_relaunch_reports_all_failed_services
	suite_addTest test_relaunch_dry_run_previews_enable_commands_without_executing
	suite_addTest test_relaunch_dry_run_previews_enable_commands_in_current_shell
	suite_addTest test_check_snapshot_rejects_snapshot_sources
	suite_addTest test_newsnap_uses_recursive_snapshot_flag
	suite_addTest test_newsnap_uses_nonrecursive_snapshot_without_r_flag
	suite_addTest test_newsnap_builds_recursive_command_in_current_shell
	suite_addTest test_newsnap_builds_nonrecursive_command_in_current_shell
	suite_addTest test_newsnap_dry_run_previews_in_current_shell
	suite_addTest test_newsnap_dry_run_previews_without_executing
	suite_addTest test_rollback_destination_to_last_common_snapshot_rolls_back_and_clears_flag
	suite_addTest test_rollback_destination_to_last_common_snapshot_skips_when_not_needed
	suite_addTest test_zxfer_reconcile_live_destination_snapshot_state_shortcuts_empty_source_and_requeues_when_live_empty
	suite_addTest test_rollback_destination_to_last_common_snapshot_reports_probe_failures
	suite_addTest test_rollback_destination_to_last_common_snapshot_reports_rollback_failures
}

zxfer_test_add_replication_snapshot_transfer_tests() {
	suite_addTest test_copy_snapshots_skips_when_no_pending_snapshots
	suite_addTest test_copy_snapshots_bootstraps_missing_destination_and_finishes_incremental
	suite_addTest test_copy_snapshots_reports_missing_destination_seed_message_to_stdout
	suite_addTest test_copy_snapshots_stops_after_seeding_single_snapshot_into_missing_destination
	suite_addTest test_copy_snapshots_rechecks_live_destination_snapshots_before_reseeding
	suite_addTest test_copy_snapshots_live_probes_initial_root_before_bootstrapping_cached_missing_destination
	suite_addTest test_copy_snapshots_uses_existing_empty_initial_root_when_cached_missing_state_is_stale
	suite_addTest test_reconcile_live_destination_snapshot_state_keeps_newest_matching_snapshot
	suite_addTest test_reconcile_live_destination_snapshot_state_fetches_source_identities_for_name_only_transfer_lists
	suite_addTest test_reconcile_live_destination_snapshot_state_refreshes_stale_common_snapshot_when_destination_already_has_snapshots
	suite_addTest test_reconcile_live_destination_snapshot_state_clears_stale_common_snapshot_when_no_live_match_remains
	suite_addTest test_reconcile_live_destination_snapshot_state_live_rechecks_cached_missing_children
	suite_addTest test_live_destination_view_one_batched_listing_serves_multiple_datasets
	suite_addTest test_live_destination_view_refreshes_after_destination_mutation_bump
	suite_addTest test_live_destination_view_listing_failure_fails_closed
	suite_addTest test_live_destination_view_reap_time_property_invalidation_bumps_generation
	suite_addTest test_live_destination_view_pass_boundary_forces_fresh_batched_listing
	suite_addTest test_reconcile_live_destination_snapshot_state_reports_source_identity_lookup_failures
	suite_addTest test_copy_snapshots_live_recheck_requires_matching_guid
	suite_addTest test_copy_snapshots_skips_send_when_live_destination_already_has_final_snapshot
	suite_addTest test_copy_snapshots_live_rechecks_empty_cached_transfer_list_before_skipping
	suite_addTest test_copy_snapshots_live_rechecks_already_final_state_before_skipping
	suite_addTest test_copy_snapshots_seeds_existing_destination_when_live_probe_confirms_no_snapshots
	suite_addTest test_copy_snapshots_reports_existing_empty_destination_seed_message_to_stdout
	suite_addTest test_copy_snapshots_ignores_descendant_snapshots_when_rechecking_parent_dataset
	suite_addTest test_copy_snapshots_reports_destination_probe_failures
	suite_addTest test_copy_snapshots_reports_live_snapshot_recheck_failures
	suite_addTest test_copy_snapshots_skips_when_last_common_matches_final_snapshot
	suite_addTest test_copy_snapshots_skips_rollback_when_deletions_left_no_new_sends
	suite_addTest test_copy_snapshots_does_not_pre_rollback_after_deletions_without_force_flag
	suite_addTest test_copy_snapshots_does_not_pre_rollback_after_older_snapshot_deletions
}

zxfer_test_add_replication_orchestration_tests() {
	suite_addTest test_validate_zfs_mode_preconditions_requires_m_for_services
	suite_addTest test_check_backup_storage_dir_if_needed_routes_local_and_remote
	suite_addTest test_check_backup_storage_dir_if_needed_returns_success_when_disabled
	suite_addTest test_check_backup_storage_dir_if_needed_refreshes_backup_root_from_environment
	suite_addTest test_check_backup_storage_dir_if_needed_dry_run_previews_without_mutating_dirs
	suite_addTest test_check_backup_storage_dir_if_needed_preserves_remote_dry_run_render_failures
	suite_addTest test_check_backup_storage_dir_if_needed_preserves_remote_dry_run_builder_failures
	suite_addTest test_check_backup_storage_dir_if_needed_rejects_relative_backup_dir_override
	suite_addTest test_run_zfs_mode_stops_before_replication_when_backup_preflight_fails
	suite_addTest test_initialize_replication_context_runs_restore_and_unsupported_scan
	suite_addTest test_initialize_replication_context_skips_unsupported_scan_for_recursive_noop_without_property_work
	suite_addTest test_initialize_replication_context_runs_unsupported_scan_for_recursive_send_work_without_property_pass
	suite_addTest test_initialize_replication_context_skips_live_validation_in_dry_run
	suite_addTest test_run_zfs_mode_calls_steps_in_order_and_relaunches_for_migration
	suite_addTest test_run_zfs_mode_dry_run_skips_live_planning_and_copy
	suite_addTest test_preview_zfs_mode_dry_run_overwrites_stale_recursive_state
	suite_addTest test_zxfer_preview_zfs_mode_dry_run_emits_restore_and_unsupported_property_notices
	suite_addTest test_perform_grandfather_protection_checks_skips_when_flag_unset
	suite_addTest test_perform_grandfather_protection_checks_calls_helpers_for_each_dataset
	suite_addTest test_perform_grandfather_protection_checks_runs_in_current_shell
	suite_addTest test_copy_filesystems_inspects_source_when_only_deletions_pending
	suite_addTest test_copy_filesystems_skips_recursive_delete_iteration_when_global_snapshot_diffs_are_empty
	suite_addTest test_copy_filesystems_shortcuts_clean_recursive_noop_before_iteration_staging
	suite_addTest test_copy_filesystems_inspects_only_datasets_with_recursive_delete_deltas
	suite_addTest test_copy_filesystems_defers_remote_control_socket_setup_until_work_exists
	suite_addTest test_copy_snapshots_seeds_existing_destination_into_snapshot
	suite_addTest test_copy_filesystems_forces_iteration_when_property_transfer_is_enabled
	suite_addTest test_copy_filesystems_property_no_snapshot_delta_does_not_send
	suite_addTest test_copy_filesystems_flushes_backup_metadata_after_snapshot_copy
	suite_addTest test_process_source_dataset_stops_after_live_backup_metadata_flush_failure
	suite_addTest test_copy_filesystems_does_not_flush_backup_metadata_when_snapshot_copy_fails
	suite_addTest test_copy_filesystems_defers_backup_metadata_flush_until_final_sync_when_send_jobs_are_pending
	suite_addTest test_copy_filesystems_promotes_deferred_backup_metadata_flush_failure
	suite_addTest test_copy_filesystems_defers_backup_metadata_flush_until_post_seed_reconcile_finishes
	suite_addTest test_copy_filesystems_does_not_flush_backup_metadata_when_post_seed_reconcile_fails
	suite_addTest test_copy_filesystems_does_not_flush_seeded_rows_during_later_completed_datasets
	suite_addTest test_copy_filesystems_reconciles_properties_after_seeding_created_destination
}

zxfer_test_add_replication_queue_failure_tests() {
	suite_addTest test_build_replication_iteration_list_merges_sources_in_current_shell
	suite_addTest test_build_replication_iteration_list_orders_siblings_before_descendants
	suite_addTest test_copy_filesystems_ready_queue_skips_blocked_descendant_for_independent_work
	suite_addTest test_copy_filesystems_ready_queue_drains_deferred_parent_child_work_in_one_run
	suite_addTest test_replication_ready_queue_preserves_pending_list_when_processing_reads_stdin
	suite_addTest test_replication_ready_queue_splits_pending_sources_when_ifs_was_narrowed
	suite_addTest test_copy_filesystems_merges_iteration_sources_and_deduplicates_post_seed_reconcile_in_current_shell
	suite_addTest test_copy_filesystems_rethrows_iteration_list_dedupe_failures
	suite_addTest test_copy_filesystems_rethrows_iteration_list_readback_failures
	suite_addTest test_copy_filesystems_reports_post_seed_property_stage_initialization_failures
	suite_addTest test_copy_filesystems_refreshes_property_tree_prefetch_context_before_iteration
	suite_addTest test_copy_filesystems_reconciles_seeded_empty_destinations_even_when_not_created_by_zxfer
	suite_addTest test_copy_filesystems_reconciles_seeded_destination_when_root_already_exists
	suite_addTest test_copy_filesystems_tracks_post_seed_reconcile_sources_in_current_shell
	suite_addTest test_copy_filesystems_rethrows_post_seed_queue_tempfile_failures
	suite_addTest test_copy_filesystems_rethrows_post_seed_queue_append_failures
	suite_addTest test_copy_filesystems_rethrows_post_seed_queue_dedupe_failures
	suite_addTest test_copy_filesystems_rethrows_post_seed_queue_readback_failures
	suite_addTest test_copy_filesystems_keeps_verbose_output_visible_while_tracking_post_seed_reconcile_sources
	suite_addTest test_copy_filesystems_resets_destination_property_cache_before_post_seed_reconcile
	suite_addTest test_copy_filesystems_keeps_destination_property_cache_across_datasets_when_background_receives_are_active
	suite_addTest test_prepare_migration_services_rejects_unmounted_sources
	suite_addTest test_prepare_migration_services_reports_mounted_probe_failures
	suite_addTest test_prepare_migration_services_live_uses_mountpoint_free_effective_readonly_list
	suite_addTest test_copy_filesystems_allows_post_unmount_migration_replication
	suite_addTest test_prepare_migration_services_relaunches_when_unmount_fails
	suite_addTest test_run_zfs_mode_loop_exits_after_single_iteration_when_no_changes
	suite_addTest test_run_zfs_mode_loop_repeats_until_changes_stop
	suite_addTest test_run_zfs_mode_loop_resets_property_cache_each_iteration
	suite_addTest test_run_zfs_mode_loop_collapses_repeated_iteration_backup_rows_at_write_boundary
	suite_addTest test_run_zfs_mode_loop_logs_hint_when_hard_iteration_limit_is_reached
	suite_addTest test_seed_destination_for_snapshot_transfer_reports_destination_probe_failures
	suite_addTest test_seed_destination_for_snapshot_transfer_reports_live_snapshot_recheck_failures
	suite_addTest test_build_replication_iteration_list_reports_second_tempfile_failures
	suite_addTest test_build_replication_iteration_list_reports_filter_command_failures
	suite_addTest test_build_replication_iteration_list_reports_stage_write_and_append_failures
	suite_addTest test_build_replication_iteration_list_reports_source_append_failures_in_current_shell
	suite_addTest test_zxfer_sort_replication_iteration_file_reports_awk_failures_in_current_shell
	suite_addTest test_build_replication_iteration_list_reports_sorted_readback_failures
	suite_addTest test_collect_post_seed_property_sources_sorts_unique_sources_in_current_shell
	suite_addTest test_append_post_seed_property_source_appends_sources_when_tracking_file_exists
	suite_addTest test_collect_post_seed_property_sources_reports_second_tempfile_failures
	suite_addTest test_collect_post_seed_property_sources_reports_first_tempfile_failures
	suite_addTest test_collect_post_seed_property_sources_reports_filter_command_failures
	suite_addTest test_collect_post_seed_property_sources_reports_sorted_readback_failures
	suite_addTest test_build_replication_iteration_list_reports_initial_tempfile_failures
	suite_addTest test_build_replication_iteration_list_reports_third_tempfile_failures
}

suite() {
	zxfer_test_add_replication_setup_migration_tests
	zxfer_test_add_replication_snapshot_transfer_tests
	zxfer_test_add_replication_orchestration_tests
	zxfer_test_add_replication_queue_failure_tests
}

# shellcheck source=tests/shunit2/shunit2
. "$SHUNIT2_BIN"
